"""create tables assets, ohlcv, analytics

Revision ID: 2bbfc88f468b
Revises: 6c84424de26e
Create Date: 2025-10-16 12:37:23.346728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbfc88f468b'
down_revision: Union[str, Sequence[str], None] = '6c84424de26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
