"""create tables assets, ohlcv, analytics

Revision ID: 6c84424de26e
Revises: 
Create Date: 2025-10-16 11:18:26.660923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c84424de26e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('idx_asset_exchange', 'assets', ['exchange'], unique=False)
    op.create_index('idx_asset_symbol', 'assets', ['symbol'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_asset_metric', 'analytics', ['asset_id', 'metric'], unique=False)
    op.create_index('idx_analytics_ts', 'analytics', ['ts'], unique=False)
    op.create_table('ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timestamp', name='uq_ohlcv_asset_timestamp')
    )
    op.create_index('idx_ohlcv_asset_timestamp', 'ohlcv', ['asset_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ohlcv_asset_timestamp', table_name='ohlcv')
    op.drop_table('ohlcv')
    op.drop_index('idx_analytics_ts', table_name='analytics')
    op.drop_index('idx_analytics_asset_metric', table_name='analytics')
    op.drop_table('analytics')
    op.drop_index('idx_asset_symbol', table_name='assets')
    op.drop_index('idx_asset_exchange', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
