name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add test commands here if you have tests
        echo "Running tests..."

    - name: Build and push Docker image
      if: github.event_name == 'push'
      run: |
        echo "Building Docker image..."
        docker build -t cryptoquant-dashboard .
        # Railway will handle deployment automatically
